In [1]:
import numpy as np

In [2]:
first_numpy_array = np.array([1,2,3,4])

In [5]:
print (first_numpy_array)

[1 2 3 4]


In [6]:
from numpy.lib import arraypad


array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
array_with_empty = np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np_arange = np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np_linspce = np.linspace(1,6,5)
print (np_linspce)

[1.   2.25 3.5  4.75 6.  ]


In [13]:
oneD_array = np.arange(15)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
twoD_array = oneD_array.reshape(3,5)
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
threeD_array = np.arange(27).reshape(3,3,3)
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])